// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHxb3ZpwBIvylCHWQl5rZqaNcVYa4Ot4',
    appId: '1:567654118983:web:bb0c4837491b268b022362',
    messagingSenderId: '567654118983',
    projectId: 'bookfinder-1719f',
    authDomain: 'bookfinder-1719f.firebaseapp.com',
    storageBucket: 'bookfinder-1719f.firebasestorage.app',
    measurementId: 'G-NGCBXEBCLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerZUatirE2-EhHrbHTcNJqc0uilVPePM',
    appId: '1:567654118983:android:5ccccb8722d476b6022362',
    messagingSenderId: '567654118983',
    projectId: 'bookfinder-1719f',
    storageBucket: 'bookfinder-1719f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xL0nOM7d77MNWJ494y5uFUZhuK2Y-os',
    appId: '1:567654118983:ios:c3225ae2712a594a022362',
    messagingSenderId: '567654118983',
    projectId: 'bookfinder-1719f',
    storageBucket: 'bookfinder-1719f.firebasestorage.app',
    androidClientId: '567654118983-v2io9phbtftdr5fb3bflgb41e9dfusem.apps.googleusercontent.com',
    iosClientId: '567654118983-brm5okh866l9qru47eetnoa5roiar8bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2xL0nOM7d77MNWJ494y5uFUZhuK2Y-os',
    appId: '1:567654118983:ios:c3225ae2712a594a022362',
    messagingSenderId: '567654118983',
    projectId: 'bookfinder-1719f',
    storageBucket: 'bookfinder-1719f.firebasestorage.app',
    androidClientId: '567654118983-v2io9phbtftdr5fb3bflgb41e9dfusem.apps.googleusercontent.com',
    iosClientId: '567654118983-brm5okh866l9qru47eetnoa5roiar8bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuHxb3ZpwBIvylCHWQl5rZqaNcVYa4Ot4',
    appId: '1:567654118983:web:537a398c738c67b7022362',
    messagingSenderId: '567654118983',
    projectId: 'bookfinder-1719f',
    authDomain: 'bookfinder-1719f.firebaseapp.com',
    storageBucket: 'bookfinder-1719f.firebasestorage.app',
    measurementId: 'G-8Z94QV3YTD',
  );

}